config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  
  devise_for :users, :controllers => {
      :sessions => 'users/sessions',
      :passwords => 'users/passwords',
      :registrations => 'users/registrations'
    }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :blogs do
    resources :comments
  end

  get 'blogs/category/:category' , to:'blogs#category', as: :category
  get 'blogs/tag/:tag' , to:'blogs#tag', as: :tag

resources :staffs do
  resources :works
end
match 'staffs/work/edit' ,:via => :post

match 'reservations/confirm' ,:via => :post
post 'reservations/list/' ,to: 'reservations#list'
get 'reservations/list/:day' ,to: 'reservations#list', as: :day
resources :reservations

get 'dashboards/blogs', to:'dashboards_blog#index' ,as: :dashboards_blog
get 'dashboards/blogs/:id/edit', to:'dashboards_blog#edit', as: :edit_dashboards_blog
put 'dashboards/blogs/:id/', to:'dashboards_blog#update', as: :update_dashboards_blog
patch 'dashboards/blogs/:id/', to:'dashboards_blog#update'
delete 'dashboards/blogs/:id/', to:'dashboards_blog#destroy', as: :delete_dashboards_blog

get 'dashboards/workday/:workday' ,to: 'dashboards#workday', as: :workday
match 'dashboards/confirm' ,:via => :post
resources :dashboards

get 'contacts' => 'contacts#index'
match 'contacts/confirm' ,:via => :post
match 'contacts/create' ,:via => :post

   root 'pages#index'

end

app/models/staff.rb
class Staff < ActiveRecord::Base
	belongs_to :user
	has_many :works
	has_many :reservations, dependent: :destroy
	# validates :name,presence: true
	# validates :email,presence: true
	# validates :address,presence: true
	# validates :age,presence: true
	# validates :hourlywage, presence: true

	mount_uploader :icon, AvatarUploader
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController

	def index
		if user_signed_in?
			@staffs = Staff.all
			@reservations = Reservation.all

			@new_work = Staff.new()
			@new_reservation = Reservation.new()
			
			@works_json =[]
			@reservations_json =[]

			@staffs.each do |staff|
				staff.works.each do |work|
				@work_data = {
				          'label' => 'staff',	
									'title' => staff.name,
									'start' => work.start.strftime("%Y-%m-%d %H:%M:%S"),
									'end' => work.end.strftime("%Y-%m-%d %H:%M:%S"),
									'backgroundColor' => '#fc0',
									'borderColor' => '#fc3',
									'img' => staff.icon.url,
									'work_id' => work.id,
									'work_staff_id' => work.staff_id,
									'work_start' => work.start,
									'work_end' => work.end
								}
				@works_json.push(@work_data)
				
				end
			end

			@reservations.each do |r|
				title = r.member.to_s+'人'
				popup = r.name+' '+r.content
				@r_data = {
					        'label' => 'reservation',
									'title' => title,
									'popup' => popup,
									'start' => r.day.strftime("%Y-%m-%d %H:%M:%S"),
									'end' => r.time.strftime("%Y-%m-%d %H:%M:%S"),
									'reservation_id' => r.id,
									'reservation_time' => r.time,
									'reservation_member' => r.member,
									'reservation_content' => r.content
								}
				@works_json.push(@r_data)

			end

		else	
			redirect_to '/'
		end
	end

	def show
		
		if Staff.find_by_id(params[:id]).present?
			@staff = Staff.find_by_id(params[:id])
		else 
			redirect_to '/staffs'
		end

		@works_json =[]
			@staff.works.each do |work|
			@work_data = {
								'title' => @staff.name,
								'start' => work.start.strftime("%Y-%m-%d %H:%M:%S"),
								'end' => work.end.strftime("%Y-%m-%d %H:%M:%S"),
								'img' => @staff.icon.url,
								'backgroundColor' => '#fc0',
								'borderColor' => '#fc3'
							}
			@works_json.push(@work_data)

			end
	end

	def edit
		if Staff.find_by_id(params[:id]).present?
			@staff = Staff.find_by_id(params[:id])
		else 
			redirect_to '/staffs'
		end
	end

	def update
    if params[:staff].present?
    	@new_staff = Staff.find(params[:id])
    	@params = staff_params
    else
    	@new_staff = Work.find(params[:work][:id])
    	@params = work_params
    end
		
    if @new_staff.update(@params)
    	redirect_to '/staffs'
    else
    	render 'edit'
    end
	end

	def destroy
		if params[:staff].present?
    	@staff = Staff.find(params[:id])
    	@params = staff_params
    else
    	@staff = Work.find(params[:work][:id])
    	@params = work_params
    end

    if @staff.destroy
    	redirect_to '/staffs'
    else
    	redirect_to staffs_path
    end

	end

	private
	  def staff_params
	  	params.require(:staff).permit(:name,:icon,:email,:address,:age,:post,:memo,:hourlywage)
	  end
	  def work_params
	  	params.require(:work).permit(:date,:start,:end,:id,:staff_id)
	  end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_detail.html.erb
<%= javascript_tag do %>
$(function(){
	$('#calendar').fullCalendar({
		lang: 'ja',
		eventRender: function(events, element) {
			if(events.img){
			    $(element[0]).find('.fc-title');
			}
    },
		header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,basicWeek,basicDay'
			},
		displayEventEnd:{
    month: true,
    basicWeek: true,
    'default': true
},	
		events: 
		<%= raw @works_json.to_json() %>
	,
		timeFormat: 'H:mm', // uppercase H for 24-hour clock

	})
	//名前消す
	$('.fc-title').css('display','none');
})
  
<% end %>

<div id="calendar"></div>

app/views/staffs/_edit_reservation.html.erb
<% if @new_reservation.errors.any? %>
    <div class="bg-danger">
      <strong>入力内容をご確認ください</strong>
      <ul class="error">
        <% @new_reservation.errors.each do |attr,msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_tag("/reservations/#{@new_reservation.id}",method: :patch,class:"form-inline") do %>
  <div class='input-group day'>
    <%= text_field :reservation,:day,class:"form-control" %>
    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
  </div>
  <div class="form-group time">
    <%= label :reservation, :time ,'利用時間' %>
    <%= text_field :reservation, :time ,class:"form-control" %>
  </div>
  <div class="form-group member">
    <%= label :reservation, :member ,'人数' %>
    <%= text_field :reservation, :member ,class:"form-control" %>
  </div>
  <div class="form-group content">
    <%= label :reservation, :content ,'プラン' %>
    <%= text_field :reservation, :content ,class:"form-control" %>
  </div>
  <div class="form-group search_btn">
    <%= button_tag '変更',class:"form-control" %>
  </div>
  <%= link_to '削除',"/reservations",class:'del form-control',method: :delete, data:{confirm:'削除します。よろしいですか？'} %>
<% end %>

app/views/staffs/_edit_staff.html.erb
<% if @new_work.errors.any? %>
  <div class="bg-danger">
    <strong>入力内容をご確認ください</strong>
    <ul class="error">
      <% @new_work.errors.each do |attr,msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_tag "/staffs/#{@new_work.id}", method: :patch,class:"form-inline" do %>
  <span class="name"></span>
  <%= hidden_field :work, :id,class:"id" %>
  <%= hidden_field :work, :staff_id,class:"staff_id" %>

  <div class='form-group date'>
    <%= label :work, :date ,'日付' %>
    <%= text_field :work ,:date ,class:"form-control" %>
  </div>            
  <div class="form-group start">
    <%= label :work, :start ,'開始時間' %>
    <%= text_field :work, :start ,class:"form-control" %>
  </div>
  <div class="form-group end">
    <%= label :work, :end ,'終了時間' %>
    <%= text_field :work, :end ,class:"form-control" %>
  </div>
  <div class="form-group submit">
    <%= button_tag '変更',class:"form-control" %>
  </div>
  <%= link_to '削除',"/staffs",class:'del form-control',method: :delete, data:{confirm:'削除します。よろしいですか？',work:'work_id'} %>
<% end %>

app/views/staffs/_schedule.html.erb
<%= javascript_tag do %>
$(function(){

	$('#calendar').fullCalendar({
		lang: 'ja',
		height:1000,
		editable: true,
		eventDrop: function(event, delta, revertFunc) {
			//移動した後のイベント

			this_data = event;
			if(this_data.label == 'staff'){
				$('.edit .staff').show();
				$('.edit .staff .name').text(this_data.title);
				$('.edit .staff .date input').val(event.start.format());
				$('.edit .staff .start input').val(event.start.format());
				$('.edit .staff .end input').val(event.end.format());
				$('.edit .staff .id').val(this_data.work_id);
				$('.edit .staff .staff_id').val(this_data.work_staff_id);

				var staff_id = this_data.work_staff_id;
				var form_action = $('.edit .staff form').attr('action');
				$('.edit .staff form').attr('action',form_action.replace(/(staffs)/,'$1/'+staff_id));
				var btn_href = $('.edit .staff .del').attr('href');
				$('.edit .staff .del').attr('href',btn_href.replace(/(staffs)/,'$1/'+staff_id+'?work[id]='+this_data.work_id));
			} else {
				$('.edit .reservation').show();
				$('.edit .reservation .name').text(this_data.title);
				$('.edit .reservation .day input').val(event.start.format());
				$('.edit .reservation .time input').val(event.end.format());
				$('.edit .reservation .member input').val(this_data.reservation_member);
				$('.edit .reservation .content input').val(this_data.reservation_content);

				var r_id = this_data.reservation_id;
				var form_action = $('.edit .reservation form').attr('action');
				$('.edit .reservation form').attr('action',form_action.replace(/(reservations)/,'$1/'+r_id));
				var btn_href = $('.edit .reservation .del').attr('href');
				$('.edit .reservation .del').attr('href',btn_href.replace(/(reservations)/,'$1/'+r_id));
			}
			
    },
    eventClick: function(calEvent) {
         alert(calEvent.popup);
    },
		eventRender: function(events, element) {
			
    },
		header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,basicWeek,basicDay'
		},
		displayEventEnd:{
		    month: true,
		    basicWeek: true,
		    'default': true
		},	
		events: 
			<%= raw @works_json.to_json() %>
		,
			timeFormat: 'H:mm', // uppercase H for 24-hour clock

		})
		
})

<% end %>
<div class="edit">
	<div class="edit_bd">
		<div class="staff">
			<%= render 'edit_staff' %>
		</div>
		<div class="reservation">
			<%= render 'edit_reservation' %>
		</div>
	</div>
</div>
<div id="calendar"></div>

app/views/staffs/edit.html.erb
<% if user_signed_in? %>
<%= render 'shared/header' %>
<section>
  <div class="contents staff Slide">
    
  	<div class="sch">
      <%#= render 'schedule' %>
    </div>
  	<div class="tbar Btn">スタッフ一覧▼</div>
  	 <div class="Inner">
     <%= form_for @staff, method: :patch,class:"form-inline" do |f| %>
      <dl class="dl_table">
				<dt class="col-xs-3">名前</dt>
        <dd class=""><%= f.text_field :name,class:"form-control" %></dd>
        <dt class="col-xs-3">アイコン</dt>
        <dd><%= f.file_field :icon %><%= f.hidden_field :icon_cache %></dd>
        <dt class="col-xs-3">メール</dt>
        <dd><%= f.text_field :email,class:"form-control" %></dd>
        <dt class="col-xs-3">住所</dt>
        <dd><%= f.text_field :address,class:"form-control" %></dd>
        <dt class="col-xs-3">年齢</dt>
        <dd><%= f.text_field :age,class:"form-control" %></dd>
        <dt class="col-xs-3">役職</dt>
        <dd><%= f.text_field :post,class:"form-control" %></dd>
        <dt class="col-xs-3">備考</dt>
        <dd><%= f.text_field :memo,class:"form-control" %></dd>
        <dt class="col-xs-3">時給</dt>
        <dd><%= f.text_field :hourlywage,class:"form-control" %></dd>
			</dl>
      <div class="tac">
        <%= button_tag '確定する',class:'btn btn-primary' %>
      </div>
     <% end %>
    </div>
  </div>
</section>
<%= render 'shared/footer' %>
<% end %>

app/views/staffs/index.html.erb
<% if user_signed_in? %>
<%= render 'shared/header' %>
<section>
  <div class="contents staff Slide">
    
  	<div class="sch">
      <%= render 'schedule' %>
    </div>
  	<div class="tbar Btn">スタッフ一覧▼</div>
  	<div class="Inner">
      <table class="staff_table">
				<tr>
					<th>名前</th>
				</tr>
				<% @staffs.each do |staff| %>
					<tr>
						<td><%= link_to staff.name,staff_path(staff) %>　<% if staff.icon? %> <%= image_tag(staff.icon, :size => "16x16") %> <% end %></td>
					</tr>
				<% end %>
			</table>
    </div>
  </div>
</section>
<%= render 'shared/footer' %>
<% end %>

app/views/staffs/show.html.erb
<% if user_signed_in? %>
<%= render 'shared/header' %>
<section>
  <div class="contents staff row">
  	<div class="tbar"><span>スタッフ詳細</span><%= link_to '編集',edit_staff_path,class:'btn btn-primary' %> <%= link_to '削除',staff_path,class:'btn btn-warning',method: :delete, data:{confirm:'削除します。よろしいですか？'} %></div>
		<table class="staff_table">
				<tr>
					<th>名前</th>
					<th>メール</th>
					<th>住所</th>
					<th>年齢</th>
					<th>役職</th>
					<th>備考</th>
					<th>時給</th>
				</tr>
				<tr>
					<td><%= @staff.name %> <%= image_tag(@staff.icon, :size => "16x16") %></td>
					<td><%= @staff.email %></td>
					<td><%= @staff.address %></td>
					<td><%= @staff.age %></td>
					<td><%= @staff.post %></td>
					<td><%= @staff.memo %></td>
					<td><%= @staff.hourlywage %></td>
				</tr>
		</table>
		
		<div class="sch detail">
			<%= render 'detail' %>
		</div>
	</div>
	<%= render 'shared/footer' %>
	<% end %>