config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  
  devise_for :users, :controllers => {
      :sessions => 'users/sessions',
      :passwords => 'users/passwords',
      :registrations => 'users/registrations'
    }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :blogs do
    resources :comments
  end

  get 'blogs/category/:category' , to:'blogs#category', as: :category
  get 'blogs/tag/:tag' , to:'blogs#tag', as: :tag

resources :staffs do
  resources :works
end
match 'staffs/work/edit' ,:via => :post

match 'reservations/confirm' ,:via => :post
post 'reservations/list/' ,to: 'reservations#list'
get 'reservations/list/:day' ,to: 'reservations#list', as: :day
resources :reservations

get 'dashboards/blogs', to:'dashboards_blog#index' ,as: :dashboards_blog
get 'dashboards/blogs/:id/edit', to:'dashboards_blog#edit', as: :edit_dashboards_blog
put 'dashboards/blogs/:id/', to:'dashboards_blog#update', as: :update_dashboards_blog
patch 'dashboards/blogs/:id/', to:'dashboards_blog#update'
delete 'dashboards/blogs/:id/', to:'dashboards_blog#destroy', as: :delete_dashboards_blog

get 'dashboards/workday/:workday' ,to: 'dashboards#workday', as: :workday
match 'dashboards/confirm' ,:via => :post
resources :dashboards

get 'contacts' => 'contacts#index'
match 'contacts/confirm' ,:via => :post
match 'contacts/create' ,:via => :post

   root 'pages#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	has_many :comments,dependent: :destroy
	mount_uploader :avatar, AvatarUploader
	validates :title, presence: true,
				  length: { minimum: 6 }
  validates :category, presence: true
  has_many :taggings,dependent: :destroy
  has_many :tags,through: :taggings

  def self.tagged_with(name)
  	Tag.find_by_name!(name).blogs
  end

  def self.tag_counts
  	Tag.select("tags.id, tags.name,count(taggings.tag_id) as count").
  	joins(:taggings).group("taggings.tag_id, tags.id, tags.name")
  end

  def tag_list
  	tags.map(&:name).join(", ")
  end

  def tag_list=(names)
  	self.tags = names.split(",").map do |n|
  		Tag.where(name: n.strip).first_or_create!
  	end	
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

	include ApplicationHelper
	before_action :get_category
	before_action :get_tags
	before_action :related_post

	def get_category
		@blogs_hava_category = Blog.where(status:true)
		@blogs_category = []
		@blogs_hava_category.each do |c|
			@blogs_category.push(c.category)
		end 
		@blogs_category = @blogs_category.uniq()
	end

	def get_tags
		@blogs = Blog.all
		@blogs_tags = []

		@blogs.each do |blog|
			if blog.status == 'public'
				if(blog.tags.any?)
					blog.tags.each do |hadTag|
						@blogs_tags.push(hadTag.name) if blog.include?
					end
				end

			end
		end
		@blogs_tags = @blogs_tags.uniq()
	end

	def category
		@categorys = Blog.where(category: params[:category])
	end

	def tag
		@tag = Tag.find_by_name(params[:tag]).blogs
	end

	def related_post
		@blog = Blog.all
	end

	def new
		@blog = Blog.new
		all_category
		all_tag
	end

	def create
		@blog = Blog.new(blogs_params)
		if @blog.save
			redirect_to @blog
		else
			all_category
			all_tag
			render 'new'
		end	
	end

	def show
		@blogs = Blog.new

		if Blog.find(params[:id]).present?
			@blog = Blog.find(params[:id])
		else 
			redirect_to '/blogs'
		end
		
	end

	def index
		@blogs = Blog.all.order("id DESC")
		@tags = Tag.all
	end

	def edit
		
		if Blog.find(params[:id]).present?
			@blog = Blog.find(params[:id])
		else 
			redirect_to '/blogs'
		end

		all_category
		all_tag
	end

	def update
		if Blog.find(params[:id]).present?
			@blog = Blog.find(params[:id])
		else 
			redirect_to '/blogs'
		end

		if @blog.update(blogs_params)
			redirect_to @blog
		else
			all_category
			all_tag
			render "edit"
		end
	end

	def destroy
		if Blog.find(params[:id]).present?
			@blog = Blog.find(params[:id])
		else 
			redirect_to '/blogs'
		end

		@blog.destroy if @blog.present?
		redirect_to blogs_path
	end

	private
		def blogs_params
			params.require(:blog).permit(:title,:text,:avatar,:category,:tag_list,:status)		
		end	

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_contents.html.erb
<article>
	<% @blogs.each do |d| %>
		<% if d.status %>	
			<%= render 'post', val: d %>
		<% end %>
	<% end %>
</article>

app/views/blogs/_form.html.erb
<%= form_for @blog, html:{class:"form-horizontal"} do |f| %>

	<% if @blog.errors.any? %>
		<div id="error_explanation">
			<ul>
				<% @blog.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
		<%= f.label 'タイトル',:class => 'control-label' %>
		<%= f.text_field :title,:class => 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label '本文',:class => 'control-label' %>
		<%= f.text_area :text,:class => 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label 'カテゴリー',:class => 'control-label' %>
		<%#= f.select :category,options_for_select(@all_category),{:prompt => 'カテゴリーを選択'}, {:class => 'form-control'} %>
		<%= f.text_field :category,:placeholder => "新規カテゴリー",:class => 'form-control inline' %>
	</div>
	<div class="form-group">
		<%= f.label 'タグ',:class => 'control-label' %>
		<%#= f.select :tag_list,options_for_select(@all_tag),{:prompt => 'タグを選択'}, {:class => 'form-control'} %>
		<%= f.text_field :tag_list,:class => 'form-control inline' %>
	</div>
	<div class="form-group avatar">
		<%= f.label '画像',:class => 'control-label' %>
		<%= f.file_field :avatar %>
		<%= f.hidden_field :avatar_cache %>
		<span><%= image_tag @blog.avatar.thumb.url if @blog.avatar? %></span>
	</div>
	<div class="form-group">
		<%= f.label '公開状態',:class => 'control-label' %>
		<%= f.select :status,[["下書き",false],["公開",true]],{},:class => 'form-control' %>
	</div>

	<%= link_to 'back',dashboards_path,:class => 'btn btn-default' %>
	<%= f.submit '送信する',:class => 'btn btn-primary' %>
<% end %> 

app/views/blogs/_post.html.erb
<div class="post">
  <h2><%= val.title %></h2>
  <div class="option">
  	<span><%= val.created_at.strftime('%Y/%m/%d') %></span>
	  <span>Category:<%= link_to val.category, category_path(val.category) %></span>
	  <% if val.tags.any? %>
	  <span>Tag:<%= raw val.tags.map(&:name).map { |t| link_to t, tag_path(t)}.join(', ') %></span>
	  <% end %>
  </div>
  <div class="article">
	  <div class="photo">
    <%= image_tag val.avatar.thumb.url if val.avatar? %></div>
	  <div class="text"><%= val.text %></div>
  </div>
  <div class="more">
  	<%= link_to '続きを見る', blog_path(val), :class => "btn btn-default" %>
  </div>
</div>
      

app/views/blogs/_side.html.erb
<aside>
  <div class="side">
	  <div class="search">
	  	<form action="">
		  	<input type="text" placeholder="検索">
		  	<button type="submit" class="btn btn-default">Search</button>
	  	</form>
	  </div>
	  <div class="box">
	  	<h3>Category</h3>
	    <ul>
		  	<% @blogs_category.each do |c| %>
	      <li><%= link_to c, category_path(c) %></li>
	      <% end %>
	    </ul>
	  </div>
	  <div class="box">
	  	<h3>Tag</h3>
	    <div class="tag_cloud">
			<% tag_cloud Blog.tag_counts, %W[s m l] do |t,css_class| %>
				<%= link_to t.name, tag_path(t.name), class: css_class %>
			<% end %>
	    </div>
	  </div>
	  
  </div>
</aside>

app/views/blogs/_sns.html.erb
<ul class="sns_btn">
	<li class="fb">
		<div class="fb-like" data-href="" data-layout="box_count" data-action="like" data-show-faces="true" data-share="false"></div>
	</li>
	<li class="tw">
		<a href="https://twitter.com/share" class="twitter-share-button" data-via="" data-lang="ja" data-dnt="true" data-count="vertical">ツイート</a>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
	</li>
	<li class="pocket">
		<a data-pocket-label="pocket" data-pocket-count="vertical" class="pocket-btn" data-lang="en"></a>
		<script type="text/javascript">!function(d,i){if(!d.getElementById(i)){var j=d.createElement("script");j.id=i;j.src="https://widgets.getpocket.com/v1/j/btn.js?v=1";var w=d.getElementById(i);d.body.appendChild(j);}}(document,"pocket-btn-js");</script>
	</li>
	<li class="hatena">
		<a href="http://b.hatena.ne.jp/entry/" class="hatena-bookmark-button" data-hatena-bookmark-title="" data-hatena-bookmark-layout="vertical-balloon" data-hatena-bookmark-lang="ja" title="このエントリーをはてなブックマークに追加"><img src="https://b.st-hatena.com/images/entry-button/button-only@2x.png" alt="このエントリーをはてなブックマークに追加" width="20" height="20" style="border: none;" /></a><script type="text/javascript" src="https://b.st-hatena.com/js/bookmark_button.js" charset="utf-8" async="async"></script>
	</li>
	<li class="gplus">
		<!-- +1 ボタン を表示したい位置に次のタグを貼り付けてください。 -->
		<div class="g-plusone" data-size="tall"></div>

		<!-- 最後の +1 ボタン タグの後に次のタグを貼り付けてください。 -->
		<script type="text/javascript">
		  window.___gcfg = {lang: 'ja'};

		  (function() {
		    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
		    po.src = 'https://apis.google.com/js/platform.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
		  })();
		</script>
	</li>
</ul>

app/views/blogs/category.html.erb
<%= render 'shared/header' %>
<section>
  <div class="contents blog row">
    <div class="postslist col-sm-12 col-md-8">
      <article>
				<% @categorys.each do |d| %>
					<% if d.status %>	
						<%= render 'post', val: d %>
					<% end %>
				<% end %>
			</article>
    </div>
    <div class="sidenavi col-sm-12 col-md-4">
      <%= render 'side' %>
    </div>
  </div>
</section>
<%= render 'shared/footer' %>

app/views/blogs/edit.html.erb
<%= render 'shared/header' %>
<div class="dash">
<h2>投稿の編集</h2>
<%= render 'form' %>
</div>
<%= render 'shared/footer' %>

app/views/blogs/index.html.erb
<%= render 'shared/header' %>
<section>
  <div class="contents blog row">
    <div class="postslist col-sm-12 col-md-8">
      <%= render 'contents' %>
    </div>
    <div class="sidenavi col-sm-12 col-md-4">
      <%= render 'side' %>
    </div>
  </div>
</section>
<%= render 'shared/footer' %>

app/views/blogs/new.html.erb
<%= render 'shared/header' %>
<div class="dash">
<h2>新規投稿</h2>
<%= render 'form' %> 
</div>
<%= render 'shared/footer' %>

app/views/blogs/show.html.erb
<%= render 'shared/header' %>
<section>
  <div class="contents blog row">
    <div class="postslist col-sm-12 col-md-8">
			<article>
				<div class="post">
				  <h2><%= @blog.title %></h2>
				  <div class="option">
				  	<span><%= @blog.updated_at.strftime('%Y/%m/%d') %></span>
					  <span>Category:<%= link_to @blog.category, category_path(@blog.category) %></span>
					  <% if @blog.tags.any? %>
					  <span>Tag:<%= raw @blog.tags.map(&:name).map { |t| link_to t, tag_path(t)}.join(', ') %></span>
					  <% end %>
				  </div>
				  <div class="box">
					  <div class="photo"><%= image_tag @blog.avatar.thumb.url if @blog.avatar? %></div>
					  <div class="text"><%= @blog.text %></div>
				  </div>
				  <%= render 'sns' %>
				</div>
			</article>
    </div>
    <div class="sidenavi col-sm-12 col-md-4">
      <%= render 'side' %>
    </div>
  </div>
</section>
<%= render 'shared/footer' %>

app/views/blogs/tag.html.erb
<%= render 'shared/header' %>
<section>
  <div class="contents blog row">
    <div class="postslist col-sm-12 col-md-8">
      <article>
				<% @tag.each do |d| %>
	      	<% if d.status %>	
						<%= render 'post', val: d %>
					<% end %>
				<% end %>
			</article>
    </div>
    <div class="sidenavi col-sm-12 col-md-4">
      <%= render 'side' %>
    </div>
  </div>
</section>
<%= render 'shared/footer' %>