config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  
  devise_for :users, :controllers => {
      :sessions => 'users/sessions',
      :passwords => 'users/passwords',
      :registrations => 'users/registrations'
    }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :blogs do
    resources :comments
  end

  get 'blogs/category/:category' , to:'blogs#category', as: :category
  get 'blogs/tag/:tag' , to:'blogs#tag', as: :tag

resources :staffs do
  resources :works
end
match 'staffs/work/edit' ,:via => :post

match 'reservations/confirm' ,:via => :post
post 'reservations/list/' ,to: 'reservations#list'
get 'reservations/list/:day' ,to: 'reservations#list', as: :day
resources :reservations

get 'dashboards/blogs', to:'dashboards_blog#index' ,as: :dashboards_blog
get 'dashboards/blogs/:id/edit', to:'dashboards_blog#edit', as: :edit_dashboards_blog
put 'dashboards/blogs/:id/', to:'dashboards_blog#update', as: :update_dashboards_blog
patch 'dashboards/blogs/:id/', to:'dashboards_blog#update'
delete 'dashboards/blogs/:id/', to:'dashboards_blog#destroy', as: :delete_dashboards_blog

get 'dashboards/workday/:workday' ,to: 'dashboards#workday', as: :workday
match 'dashboards/confirm' ,:via => :post
resources :dashboards

get 'contacts' => 'contacts#index'
match 'contacts/confirm' ,:via => :post
match 'contacts/create' ,:via => :post

   root 'pages#index'

end

app/views/shared/_footer.html.erb
		<footer>
		  <div class="footer row">
		    <p class="col-sm-12">&copy; writer</p>
		  </div>  
		</footer>

app/views/shared/_header.html.erb
		<header>
			<div class="header row">
				<h1><%= link_to 'Shop name',root_path %></h1>
				<div class="smart"><span class="glyphicon glyphicon-align-justify" aria-hidden="true"></span></div>
				<nav>
					<ul class="nav nav-pills pull-right">
						<li><%= link_to 'ブログ', blogs_path %></li>
						<li><%= link_to '予約', reservations_path %></li>
						<li><a href="/">EC Shop</a></li>
						<li><%= link_to 'お問い合わせ', contacts_path %></li>
				<% if user_signed_in? %>
					<% if can? :manage, Staff %>
						<li><%= link_to '管理画面', staffs_path %></li>
					<% end %>
						<li><%= link_to 'シフト管理', dashboards_path %></li>
						<li><%= link_to 'ログアウト',destroy_user_session_path,method: :delete,:class => 'signout' %></li>
				<% else  %>
						<li><%= link_to 'ログイン',new_user_session_path,:class => 'signin' %></li>
				<% end %>
					</ul>
				</nav>
			</div>
		</header>