config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  
  devise_for :users, :controllers => {
      :sessions => 'users/sessions',
      :passwords => 'users/passwords',
      :registrations => 'users/registrations'
    }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :blogs do
    resources :comments
  end

  get 'blogs/category/:category' , to:'blogs#category', as: :category
  get 'blogs/tag/:tag' , to:'blogs#tag', as: :tag

resources :staffs do
  resources :works
end
match 'staffs/work/edit' ,:via => :post

match 'reservations/confirm' ,:via => :post
post 'reservations/list/' ,to: 'reservations#list'
get 'reservations/list/:day' ,to: 'reservations#list', as: :day
resources :reservations

get 'dashboards/blogs', to:'dashboards_blog#index' ,as: :dashboards_blog
get 'dashboards/blogs/:id/edit', to:'dashboards_blog#edit', as: :edit_dashboards_blog
put 'dashboards/blogs/:id/', to:'dashboards_blog#update', as: :update_dashboards_blog
patch 'dashboards/blogs/:id/', to:'dashboards_blog#update'
delete 'dashboards/blogs/:id/', to:'dashboards_blog#destroy', as: :delete_dashboards_blog

get 'dashboards/workday/:workday' ,to: 'dashboards#workday', as: :workday
match 'dashboards/confirm' ,:via => :post
resources :dashboards

get 'contacts' => 'contacts#index'
match 'contacts/confirm' ,:via => :post
match 'contacts/create' ,:via => :post

   root 'pages#index'

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

include ApplicationHelper

	def index
		setUser(current_user.username)
		workList

		@blogs = Blog.all
	end

	def show
		@staff_data = User.find(params[:id]).staff
		workList
	end

	def new
		@new_work = Work.new
		halfMonth
		@bisnesstime = ApplicationHelper::STAFF_START_TIME..ApplicationHelper::STAFF_END_TIME
	end

	def workday
		@new_work = Work.new
		@new_work.date = params[:workday]
		
		@worktimes = []
		num = 0

		while num < ApplicationHelper::STAFF_END_TIME-ApplicationHelper::STAFF_START_TIME do
			@worktimes.push([ApplicationHelper::STAFF_START_TIME+num,@new_work.date+(ApplicationHelper::STAFF_START_TIME+num).hour])
			num = num+1
		end
	end	

	def confirm
		works = work_params
		@works =[]

		works.each do |w|

			work = Work.new(w)
			@works.push(work)
		end

  	halfMonth

  	#if @works.valid?
  		render :action => 'confirm'
  	# else
  	# 	@new_work = @works
  	# 	render :action => 'new'
  	# end
	end

	def create

		@works =[]

		work_params.each do |w|
			unless w[:start].empty?
				work = Work.new(w)
				@works.push(work)
			end
		end

		@works.each do |w|
			if w.valid?
				w.save
			end
		end
		
		#メール送信
  	#ContactMailer.received_email(@new_reservation).deliver
		render :action => 'create'
	end

	def edit

		if User.find(params[:id]).staff.present?
			@staff_data = User.find(params[:id]).staff
		else 
			redirect_to '/dashboards'
		end

		@staff_reservations = Reservation.where(:staff_id=>@staff_data[:id])

	end

	def update
		
		if Staff.find(params[:staff][:id]).present?
			@staff_update = Staff.find(params[:staff][:id])
		else 
			redirect_to '/dashboards'
		end

		if @staff_update.update(staff_params)
			redirect_to dashboard_path
		else
			render "dashboards/edit"
		end
	end

	def destroy

		if Blog.find(params[:id]).present?
			@blog = Blog.find(params[:id])
		else 
			redirect_to '/dashboards'
		end
		
		@blog.destroy
		redirect_to blogs_path
	end

	 private
		def blogs_params
			params.require(:blog).permit(:title,:text,:avatar,:tag_list)	
		end

		def staff_params
			params.require(:staff).permit(:name,:email,:address,:age,:hourlywage)	
		end
		
		def work_params
			params.require(:work).map do |param|
				ActionController::Parameters.new(param.to_hash).permit(:date,:start,:end,:break,:staff_id)
			end
		end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_blog.html.erb
<div id="blog">
	<h3>Blog</h3>
	<div class="new">
		<p><%= link_to '新規投稿',new_blog_path, :class => "btn btn-primary" %></p>	
	</div>

	<div class="table-responsive">
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>タイトル</th>
					<th>状態</th>
					<th>カテゴリー</th>
					<th>タグ</th>
					<th>コメント</th>
					<th>日時</th>
				</tr>
			</thead>
			<tbody>
			<% @blogs.each do |blog|  %>
				<tr>
					<td><%= link_to blog.title, blog_path(blog) %>
						<div><%= link_to '編集', edit_blog_path(blog), :class => "btn btn-primary" %> <%= link_to '削除', blog_path(blog), :class => "btn btn-warning" , method: :delete,data:{confirm:"この記事を削除してもよろしいですか?"} %></div>
					</td>
					<td><%= blog.status? ? '公開':'下書き' %></td>
					<td><%= blog.category %></td>
					<td><%= blog.tags.map(&:name).map {|t| t}.join(', ') %></td>
					<td><%= blog.comments.any? ? 'あり':'なし' %></td>
					<td><%= blog.updated_at.strftime('%Y/%m/%d %H:%M:%S')  %></td>
				</tr>
			<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/dashboards/_header.html.erb
<%= javascript_tag do %>
$(function(){
	$('#calendar').fullCalendar({
		lang: 'ja',
		height:700,
		eventRender: function(events, element) {
			$(element[0]).find('.fc-time').html(events.name);
    },

		header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,basicWeek,basicDay'
			},
		displayEventEnd:{
    month: true,
    basicWeek: true,
    'default': true
},	
		events: 
		<%= raw @work_list.to_json() %>,
		dayClick: function(date, jsEvent, view) {
				location.href = '/dashboards/workday/' + date.format();
    }
	,
		timeFormat: 'H:mm', // uppercase H for 24-hour clock

	})

})
  
<% end %>
<div class="dash">
	<div class="title">
		<h2>Dashboard<strong>:<%= current_user.username %></strong></h2>
	</div>

	<ul class="navi row">
		<li class="col-xs-3"><%= link_to 'Blog',{ :anchor => "blog"}, :class => 'btn btn-default' %></li>
		<li class="col-xs-3"><%= link_to 'シフト登録', new_dashboard_path(),:class => 'btn btn-default' %></li>
		<li class="col-xs-3"><%= link_to '登録情報',edit_dashboard_path(current_user[:id]),:class => 'btn btn-default' %></li>
		<li class="col-xs-3"><%= mail_to 'user@example.com','メールで連絡する',:class => 'btn btn-default' %></li>
	</ul>

	

	<div id="calendar"></div>
</div>

app/views/dashboards/confirm.html.erb
<%= render 'shared/header' %>
<script type="text/javascript">
    $(function () {
        $('button').click(function(){
          window.history.back(-1);
          return false;
        });
    });
</script>
<section>
  <div class="contents works row">
    <p>以下の日時で登録します。よろしいですか？</p>
      <%= form_for @works,:url => dashboards_path,html:{class:"form-group"} do |f| %>
        <table class="table table-bordered">
          <tr class="active">
            <th><%= f.label '日時' %></th>
            <th><%= f.label '開始時間' %></th>
            <th><%= f.label '終了時間' %></th>
          </tr>
         <% @works.each do |work| %>
           <%= fields_for 'work[]',work,index: nil do |fh| %>
            <tr>
              <td><%= fh.hidden_field :date %><%= work.date.strftime("%Y/%m/%d") %></td>
              <td><%= fh.hidden_field :start %><%= work.start.try(:strftime, "%Y/%m/%d %H:%M")  %></td>
              <td>
                  <%= fh.hidden_field :end %><%= work.end.try(:strftime, "%Y/%m/%d %H:%M")  %>
                  <%= fh.hidden_field :break %>
                  <%= fh.hidden_field :staff_id %>
              </td>
            </tr>
           <% end %>
         <% end %>
        </table>
        <p class="tac">
          <%= button_tag(type: 'button',class:"btn btn-default") do
            content_tag(:span, '戻る')
          end %>
          <%= f.submit '送信',class:"btn btn-default" %>
        </p>
    <% end %>
  </div>
</section>
<%= render 'shared/footer' %>

app/views/dashboards/create.html.erb
<%= render 'shared/header' %>

<p>登録しました。</p>
<%= link_to "Dashboradへ戻る", dashboards_path() %>

<%= render 'shared/footer' %>

app/views/dashboards/edit.html.erb
<% if user_signed_in? %>
<%= render 'shared/header' %>
<div class="dash">
	<div class="title">
		<h2>Dashboard<strong>:<%= current_user.username %></strong></h2>
	</div>

	<h3>登録情報</h3>
	<% if @staff_data.errors.any? %>
    <div class="bg-danger">
      <strong>入力内容をご確認ください</strong>
      <ul class="error">
        <% @staff_data.errors.each do |attr,msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
	<% end %>

	<%= form_for @staff_data,:url => dashboard_path,html:{class:"form-group"} do |f| %>
    <div class="block">
			<%= f.hidden_field :id %>
	    <div class="form-group name">
	        <%= f.label 'お名前' %><%= f.text_field :name, class: "form-control" %>
	    </div>
	    <div class="form-group mail">
	        <%= f.label 'メールアドレス' %><%= f.text_field :email, class: "form-control" %>
	    </div>
	    <div class="form-group address">
	        <%= f.label '住所' %><%= f.text_field :address, class: "form-control" %>
	    </div>
	    <div class="form-group age">
	        <%= f.label '年齢' %><%= f.text_field :age, class: "form-control" %>
	    </div>
	    <div class="form-group icon">
	        <%= f.label 'アイコン' %>
	        <%= f.file_field :icon %>
					<%= f.hidden_field :icon_cache %>
					<span><%= image_tag @staff_data.icon.thumb.url if @staff_data.icon? %></span>
	    </div>
	    <% @staff_data.reservations %>
	    <div class="form-group post">
	        <%#= f.label '役職' %><%#= f.text_field :post, class: "form-control" %>
	    </div>
	    <div class="form-group memo">
	        <%#= f.label '備考' %><%#= f.text_field :memo, class: "form-control" %>
	    </div>
	    <div class="form-group memo">
	        <%#= f.label '時給' %><%#= f.text_field :hourlywage, class: "form-control" %>
	    </div>
	    <div type="submit" class="form-group tac">
	    	<%= f.submit '編集する',class:"btn btn-default" %>
			  <%#= button_tag(type: 'submit',class:"btn btn-default") do
          content_tag(:span, '編集する')
        end %>
	    </div>
    </div>
	<% end %>	
</div>

<%= render 'shared/footer' %>
<% end %>

app/views/dashboards/index.html.erb
<% if user_signed_in? %>
<%= render 'shared/header' %>

<%= render 'header' %>
<%= render 'blog' %>

<%= render 'shared/footer' %>
<% end %>

app/views/dashboards/new.html.erb
<% if user_signed_in? %>
<%= render 'shared/header' %>

<div class="dash">
	<div class="title">
		<h2>Dashboard<strong>:<%= current_user[:username] %></strong></h2>
	</div>

		<h3>シフト登録</h3>
		<% if @new_work.errors.any? %>
		    <div class="bg-danger">
	        <strong>入力内容をご確認ください</strong>
	        <ul class="error">
            <% @new_work.errors.each do |attr,msg| %>
              <li><%= msg %></li>
            <% end %>
	        </ul>
		    </div>
		<% end %>
	
	<%= form_tag('/dashboards/confirm',class:"form-inline") do %>
	    
    <!-- 2週間分を登録申請 -->
    <% @days.each do |day| %>

	    <% 
	    	@worktimes = []
		    @bisnesstime.each { |n| @worktimes.push([n,day+n.hour]) }
	     %>
			<%= fields_for 'work[]',day,index: nil do |fh| %>
			<%= fh.hidden_field :staff_id,:value => current_user.staff[:id] %>

		    <div class="block">
			    <div class='input-group date'>
				    <%= day.strftime('%Y-%m-%d') %>
				    <%= fh.hidden_field :date,:value => day.strftime('%Y-%m-%d') %>
			    </div>				    
			    <div class="form-group time start">
				    <%= select_tag 'work[][start]', options_for_select(@worktimes),:selected => @new_work.start.to_s,:prompt => '開始時間を選択',:class => 'form-control' %>
			    </div>
			    <div class="form-group time end">
				    <%= select_tag 'work[][end]', options_for_select(@worktimes),:selected => @new_work.start.to_s,:prompt => '終了時間を選択',:class => 'form-control' %>
			    </div>
		    </div>
				    <%= fh.hidden_field :break,:value => (day+1.hour).strftime('%Y-%m-%d %H:%M') %>
			<% end %>
		<% end %>
		
    <div class="tac">
      <%= button_tag(type: 'submit',class:"btn btn-default") do
        content_tag(:span, '確認画面へ')
      end %>
    </div>
	<% end %>
</div>

<%= render 'shared/footer' %>
<% end %>

app/views/dashboards/show.html.erb
<% if user_signed_in? %>
<%= render 'shared/header' %>

<%= render 'header' %>

<%= render 'shared/footer' %>
<% end %>

app/views/dashboards/workday.html.erb
<% if user_signed_in? %>
<%= render 'shared/header' %>
<div class="dash">
	<div class="title">
		<h2>Dashboard<strong>:<%= current_user.username %></strong></h2>
	</div>

	<h3>シフト登録</h3>
	<% if @new_work.errors.any? %>
    <div class="bg-danger">
      <strong>入力内容をご確認ください</strong>
      <ul class="error">
        <% @new_work.errors.each do |attr,msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
	<% end %>

	<%= form_tag('/dashboards/confirm',class:"form-inline") do %>
		<%= fields_for 'work[]',@new_work,index: nil do |fh| %>
	    <%= fh.hidden_field :staff_id,:value => current_user.staff[:id] %>
		    <div class="block">
			    <div class='input-group date'>
				    <%= @new_work.date.strftime('%Y-%m-%d') %>
				    <%= fh.hidden_field :date,:value => @new_work.date.strftime('%Y-%m-%d') %>
			    </div>
			    <div class="form-group time start">
			    	<%= select_tag 'work[][start]', options_for_select(@worktimes),:selected => @new_work.start.to_s,:prompt => '開始時間を選択',:class => 'form-control' %>
			    </div>
			    <div class="form-group time end">
			    	<%= select_tag 'work[][end]', options_for_select(@worktimes),:selected => @new_work.start.to_s,:prompt => '終了時間を選択',:class => 'form-control' %>
			    </div>
			    <div type="submit" class="form-group">
					  <%= fh.hidden_field :break,:value => (@new_work.date+1.hour).strftime('%Y-%m-%d %H:%M') %>
					  <%= button_tag(type: 'submit',class:"btn btn-default") do
		          content_tag(:span, '確認画面へ')
		        end %>
			    </div>
		    </div>
		  <% end %>
	<% end %>	
</div>

<%= render 'shared/footer' %>
<% end %>